### ISSUE TITLE
Loss for KL 

### ISSUE THREAD

**Issue by anitaweng** [tienmanhptit1312/Disentangle-VAE-for-VC#5]
Hi, it is a nice work.
There is a question I want to ask.
Why [here](https://github.com/v-manhlt3/Disentangle-VAE-for-VC/blob/c8b5ce8f6bd0c8b5e9f1ec2a74bd2e7817c6fe77/model/disentangled_vae.py#L279) returns `content_mu1, content_logvar1, content_mu2, content_logvar2` instead of  `q_z1_mu, q_z1_logvar, q_z2_mu, q_z2_logvar`?
[Here](https://github.com/v-manhlt3/Disentangle-VAE-for-VC/blob/c8b5ce8f6bd0c8b5e9f1ec2a74bd2e7817c6fe77/model/variational_base_vae.py#L58), the step function updates the loss, and according to the paper, in equation 7, the latent vector z should be the  one that is concatenated.
I am confused about this. It will be great if you can reply to me.

**Comment by v-manhlt3** [comment]
Hi,
Regarding your first question, it should return `q_z1_mu, q_z1_logvar, q_z2_mu, q_z2_logvar`. Thank you to point out that mistake.

About your second question, there are two latent vectors `z1 and z2` which represent a pair of utterances. In the Eq. 7 for the KL terms, it should be `(q_φ(z1|x1) and (q_φ(z2|x2)` instead of `(q_φ(z|x1) and (q_φ(z|x2)`, so in my paper, it is a typo.

**Comment by anitaweng** [comment]
> Hi, Regarding your first question, it should return `q_z1_mu, q_z1_logvar, q_z2_mu, q_z2_logvar`. Thank you to point out that mistake.
> 
> About your second question, there are two latent vectors `z1 and z2` which represent a pair of utterances. In the Eq. 7 for the KL terms, it should be `(q_φ(z1|x1) and (q_φ(z2|x2)` instead of `(q_φ(z|x1) and (q_φ(z|x2)`, so in my paper, it is a typo.

OK,
Thanks for your reply.

**Comment by anitaweng** [comment]
Hi,
I have another question to ask. Will this mistake change the outcome?
